# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# This re-usable component runs a test

name: test

on:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # needed for cache
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: test
        run: go test -v ./...
        # run: make test
      # use this option to share coverage reports with team members
      # - name: coverage check
      #   run: make coverage
      # - name: make report
      #   run: make report
      # - name: copy files
      #   run: |
      #     mkdir reports
      #     cp cover.html reports/
      # - name: archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: reports
      #     path: reports
